# Config file saving all important settings that have been set; A recovery to default mode is possible

%YAML 1.1

import getpass
import os, sys

---
folders:
  dpedr: 'D:\\DBS_patients'
  Anwender: 'C:\Users\Anwender\PycharmProjects\pythonProject'
