import sys
from PyQt5 import QtCore

from PyQt5.QtWidgets import QApplication, QDialog, QPushButton, QVBoxLayout, QGroupBox, \
    QHBoxLayout, QFileDialog, QWidget, QRadioButton, QGridLayout


class PostoperativeDialog(QDialog):
    """Dialog."""

    def __init__(self, parent=None):
        """Initializer."""
        super(PostoperativeDialog, self).__init__(parent)

        grid = QGridLayout(self)
        grid.addWidget(self.createGroup1(), 0, 0)
        grid.addWidget(self.createGroup2(), 0, 1)
        grid.addWidget(self.createGroup3(), 0, 2)
        grid.addWidget(self.createGroup4(), 1, 0)
        grid.addWidget(self.createGroup5(), 1, 1)
        grid.addWidget(self.createGroup6(), 1, 2)
        grid.addWidget(self.createGroup7(), 2, 0)
        grid.addWidget(self.createGroup8(), 2, 1)
        grid.addWidget(self.createGroup9(), 2, 2)
        grid.addWidget(self.createGroup10(), 3, 0)
        self.setLayout(grid)

        self.setWindowTitle('Patients Information')
        self.setGeometry(200, 100, 280, 170)
        self.move(850, 200)

# Groups
    def createGroup1(self):
        groupBox1 = QGroupBox("Basic Information")
        info1 = QRadioButton("PID")
        info2 = QRadioButton("ID")
        info3 = QRadioButton("Gender")
        info4 = QRadioButton("Diagnosis")
        info1.setChecked(True)
        info2.setChecked(True)
        info3.setChecked(True)
        info4.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info1)
        vbox.addWidget(info2)
        vbox.addWidget(info3)
        vbox.addWidget(info4)
        vbox.addStretch(1)
        groupBox1.setLayout(vbox)
        return groupBox1

    def createGroup2(self):
        groupBox2 = QGroupBox("Admissions/Dismissions")
        info5 = QRadioButton("Admission_NCh")
        info6 = QRadioButton("Dismissal_NCh")
        info7 = QRadioButton("Admission_NR")
        info8 = QRadioButton("Dismissal_NR")
        info5.setChecked(True)
        info6.setChecked(True)
        info7.setChecked(True)
        info8.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info5)
        vbox.addWidget(info6)
        vbox.addWidget(info7)
        vbox.addWidget(info8)
        vbox.addStretch(1)
        groupBox2.setLayout(vbox)
        return groupBox2

    def createGroup3(self):
        groupBox3 = QGroupBox("Reports")
        info9 = QRadioButton("Report_File_NCh")
        info10 = QRadioButton("Report_File_NR")
        info11 = QRadioButton("Reason")
        info9.setChecked(True)
        info10.setChecked(True)
        info11.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info9)
        vbox.addWidget(info10)
        vbox.addWidget(info11)
        vbox.addStretch(1)
        groupBox3.setLayout(vbox)
        return groupBox3

    def createGroup4(self):
        groupBox4 = QGroupBox("Scans/Dates")
        info12 = QRadioButton("Using_Programmer")
        info13 = QRadioButton("CTscan")
        info14 = QRadioButton("Battery_Replacement")
        info15 = QRadioButton("Planned_Visit")
        info16 = QRadioButton("Qualipa_Visit")
        info17 = QRadioButton("Surgery_Date")
        info12.setChecked(True)
        info13.setChecked(True)
        info14.setChecked(True)
        info15.setChecked(True)
        info16.setChecked(True)
        info17.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info12)
        vbox.addWidget(info13)
        vbox.addWidget(info14)
        vbox.addWidget(info15)
        vbox.addWidget(info16)
        vbox.addWidget(info17)
        vbox.addStretch(1)
        groupBox4.setLayout(vbox)
        return groupBox4

    def createGroup5(self):
        groupBox5 = QGroupBox("LEDD")
        info18 = QRadioButton("LEDD")
        info18.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info18)
        vbox.addStretch(1)
        groupBox5.setLayout(vbox)
        return groupBox5

    def createGroup6(self):
        groupBox6 = QGroupBox("Medication")
        info19 = QRadioButton("Levodopa/Carbidopa")
        info20 = QRadioButton("Levodopa/Carbidopa CR")
        info21 = QRadioButton("Entacapone")
        info22 = QRadioButton("Tolcapone")
        info23 = QRadioButton("Pramipexole")
        info24 = QRadioButton("Ropinirole")
        info25 = QRadioButton("Rotigotine")
        info26 = QRadioButton("Selegiline, oral")
        info27 = QRadioButton("Selegiline, sublingual")
        info28 = QRadioButton("Rasagiline")
        info29 = QRadioButton("Amantadine")
        info30 = QRadioButton("Apomorphine")
        info31 = QRadioButton("Piribedil")
        info32 = QRadioButton("Safinamid")
        info33 = QRadioButton("Opicapone")
        info34 = QRadioButton("Other")
        info19.setChecked(True)
        info20.setChecked(True)
        info21.setChecked(True)
        info22.setChecked(True)
        info23.setChecked(True)
        info24.setChecked(True)
        info25.setChecked(True)
        info26.setChecked(True)
        info27.setChecked(True)
        info28.setChecked(True)
        info29.setChecked(True)
        info30.setChecked(True)
        info31.setChecked(True)
        info32.setChecked(True)
        info33.setChecked(True)
        info34.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info19)
        vbox.addWidget(info20)
        vbox.addWidget(info21)
        vbox.addWidget(info22)
        vbox.addWidget(info23)
        vbox.addWidget(info24)
        vbox.addWidget(info25)
        vbox.addWidget(info19)
        vbox.addWidget(info20)
        vbox.addWidget(info21)
        vbox.addWidget(info22)
        vbox.addWidget(info23)
        vbox.addWidget(info24)
        vbox.addWidget(info25)
        vbox.addWidget(info26)
        vbox.addWidget(info27)
        vbox.addWidget(info28)
        vbox.addWidget(info29)
        vbox.addWidget(info30)
        vbox.addWidget(info31)
        vbox.addWidget(info32)
        vbox.addWidget(info33)
        vbox.addWidget(info34)
        vbox.addStretch(1)
        groupBox6.setLayout(vbox)
        return groupBox6

    def createGroup7(self):
        groupBox7 = QGroupBox("UPDRS")
        info35 = QRadioButton("UPDRS_On")
        info36 = QRadioButton("UPDRS_Off")
        info37 = QRadioButton("UPDRS I")
        info38 = QRadioButton("UPDRS II")
        info39 = QRadioButton("UPDRS III_On")
        info40 = QRadioButton("UPDRS III_Off")
        info41 = QRadioButton("UPDRS IV")
        info35.setChecked(True)
        info36.setChecked(True)
        info37.setChecked(True)
        info38.setChecked(True)
        info39.setChecked(True)
        info40.setChecked(True)
        info41.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info35)
        vbox.addWidget(info36)
        vbox.addWidget(info37)
        vbox.addWidget(info38)
        vbox.addWidget(info39)
        vbox.addWidget(info40)
        vbox.addWidget(info41)
        vbox.addStretch(1)
        groupBox7.setLayout(vbox)
        return groupBox7

    def createGroup8(self):
        groupBox8 = QGroupBox("Care/Test")
        info42 = QRadioButton("TRS_On")
        info43 = QRadioButton("TRS_Off")
        info44 = QRadioButton("H&Y")
        info45 = QRadioButton("EQ5D")
        info46 = QRadioButton("MoCa")
        info47 = QRadioButton("DemTect")
        info48 = QRadioButton("TSS")
        info49 = QRadioButton("CGIG_Clinician_Cargiver")
        info50 = QRadioButton("CGIG_Patient")
        info51 = QRadioButton("MMST")
        info52 = QRadioButton("PDQ8")
        info53 = QRadioButton("BDI2")
        info54 = QRadioButton("PDQ39")
        info55 = QRadioButton("NMSQ")
        info56 = QRadioButton("S&E")
        info42.setChecked(True)
        info43.setChecked(True)
        info44.setChecked(True)
        info45.setChecked(True)
        info46.setChecked(True)
        info47.setChecked(True)
        info48.setChecked(True)
        info49.setChecked(True)
        info50.setChecked(True)
        info51.setChecked(True)
        info52.setChecked(True)
        info53.setChecked(True)
        info54.setChecked(True)
        info55.setChecked(True)
        info56.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info42)
        vbox.addWidget(info43)
        vbox.addWidget(info44)
        vbox.addWidget(info45)
        vbox.addWidget(info46)
        vbox.addWidget(info47)
        vbox.addWidget(info48)
        vbox.addWidget(info49)
        vbox.addWidget(info50)
        vbox.addWidget(info51)
        vbox.addWidget(info52)
        vbox.addWidget(info53)
        vbox.addWidget(info54)
        vbox.addWidget(info55)
        vbox.addWidget(info56)
        vbox.addStretch(1)
        groupBox8.setLayout(vbox)
        return groupBox8

    def createGroup9(self):
        groupBox9 = QGroupBox("Perc")
        info57 = QRadioButton("Perc1")
        info58 = QRadioButton("Perc2")
        info59 = QRadioButton("Perc3")
        info60 = QRadioButton("Perc4")
        info61 = QRadioButton("Perc5")
        info62 = QRadioButton("Perc6")
        info63 = QRadioButton("Perc7")
        info64 = QRadioButton("Perc8")
        info65 = QRadioButton("Perc9")
        info66 = QRadioButton("Perc10")
        info67 = QRadioButton("Perc11")
        info68 = QRadioButton("Perc12")
        info69 = QRadioButton("Perc13")
        info70 = QRadioButton("Perc14")
        info71 = QRadioButton("Perc15")
        info72 = QRadioButton("Perc16")
        info57.setChecked(True)
        info58.setChecked(True)
        info59.setChecked(True)
        info60.setChecked(True)
        info61.setChecked(True)
        info62.setChecked(True)
        info63.setChecked(True)
        info64.setChecked(True)
        info65.setChecked(True)
        info66.setChecked(True)
        info67.setChecked(True)
        info68.setChecked(True)
        info69.setChecked(True)
        info70.setChecked(True)
        info71.setChecked(True)
        info72.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info57)
        vbox.addWidget(info58)
        vbox.addWidget(info59)
        vbox.addWidget(info60)
        vbox.addWidget(info61)
        vbox.addWidget(info62)
        vbox.addWidget(info63)
        vbox.addWidget(info64)
        vbox.addWidget(info65)
        vbox.addWidget(info66)
        vbox.addWidget(info67)
        vbox.addWidget(info68)
        vbox.addWidget(info69)
        vbox.addWidget(info70)
        vbox.addWidget(info71)
        vbox.addWidget(info72)
        vbox.addStretch(1)
        groupBox9.setLayout(vbox)
        return groupBox9

    def createGroup10(self):
        groupBox10 = QGroupBox("Other")
        info73 = QRadioButton("AmplL")
        info74 = QRadioButton("AmplR")
        info75 = QRadioButton("PWL")
        info76 = QRadioButton("PWR")
        info77 = QRadioButton("FreqL")
        info78 = QRadioButton("FreqR")
        info79 = QRadioButton("AE")
        info80 = QRadioButton("Comments")
        info73.setChecked(True)
        info74.setChecked(True)
        info75.setChecked(True)
        info76.setChecked(True)
        info77.setChecked(True)
        info78.setChecked(True)
        info79.setChecked(True)
        info80.setChecked(True)
        vbox = QVBoxLayout()
        vbox.addWidget(info73)
        vbox.addWidget(info74)
        vbox.addWidget(info75)
        vbox.addWidget(info76)
        vbox.addWidget(info77)
        vbox.addWidget(info78)
        vbox.addWidget(info79)
        vbox.addWidget(info80)
        vbox.addStretch(1)
        groupBox10.setLayout(vbox)
        return groupBox10

# ====================    Create Content for Buttons at the Bottom      ====================
        layout_bottom = QHBoxLayout()
        self.button_save_return = QPushButton('Save settings \nand return')
        self.button_save_return.clicked.connect(self.onClickedSaveReturn)
        self.button_close = QPushButton('Save and \nclose')
        self.button_close.clicked.connect(self.close)

        layout_bottom.addStretch(1)
        layout_bottom.addWidget(self.button_save_return)
        layout_bottom.addWidget(self.button_close)

        self.layout.addWidget(self.optionbox1)
        self.layout.addLayout(layout_bottom)

    # In the next lines, actions are defined when Buttons are pressed
    @QtCore.pyqtSlot()
    def onClickedSaveReturn(self):
        self.saveFileDialog()

    def close(self):
        self.saveFileDialog()

    def saveFileDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getSaveFileName(self, "QFileDialog.getSaveFileName()", "test.txt", "All Files(*)", options=options)
        print(fileName)

    # for opening
    def open_dialog_box (self):
        option = QFileDialog.Options()
        # first parameter is self; second is the Window Title, third title is Default File Name, fourth is FileType,
        # fifth is options
        file = QFileDialog.getOpenFileName(self, "Save File Window Title", "default.txt", "All Files (*)", options=option)
        print(file)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    widget = QWidget
    dlg = PostoperativeDialog()
    dlg.show()
    sys.exit(app.exec_())

